[phases.setup]
aptPkgs = ['unzip', 'curl']
nixPkgs = ['nodejs_22', 'bun']

[phases.install]
cmds = [
  'nix-env -iA nixpkgs.bun',
  'bun --version',
  'bun install'
]

[phases.build]
cmds = [
  'export BUN_INSTALL="$HOME/.bun"',
  'export PATH="$BUN_INSTALL/bin:$PATH"',
  'bun install',
  'bun run build'
]

[start]
cmd = 'bun run start'
