[phases.setup]
aptPkgs = ['unzip', 'curl']
nixPkgs = ['nodejs_22', 'bun']

[phases.install]
cmds = [
  'curl -fsSL https://bun.sh/install | bash',
  '. "$HOME/.bun/bin/env"',
  'bun install'
]

[phases.build]
cmds = ['bun run build']

[start]
cmd = 'bun run start'
