[phases.setup]
aptPkgs = ['unzip', 'curl']
nixpkgs = ['nodejs_22', 'bun']

[phases]
# Use Bun to install dependencies
build = "bun install"
# Use Bun to start the application
start = "bun start"

[start]
cmd = 'bun run start'
