[phases.setup]
aptPkgs = ['unzip', 'curl']
nixPkgs = ['nodejs_22', 'bun']

[phases.install]
cmds = [
  'curl -fsSL https://bun.sh/install | bash',
  'export BUN_INSTALL="$HOME/.bun"',
  'export PATH="$BUN_INSTALL/bin:$PATH"',
  'echo "export PATH=\"$BUN_INSTALL/bin:$PATH\"" >> $HOME/.bashrc',
  'source $HOME/.bashrc',
  'ln -s $HOME/.bun/bin/bun /usr/local/bin/bun'
   'ls -l $HOME/.bun/bin/bun',
  'chmod +x $HOME/.bun/bin/bun'
]

[phases.build]
cmds = [
  'export BUN_INSTALL="$HOME/.bun"',
  'export PATH="$BUN_INSTALL/bin:$PATH"',
  'bun install',
  'bun run build'
]

[start]
cmd = 'bun run start'
