[phases.setup]
aptPkgs = ['unzip', 'curl']
nixPkgs = ['nodejs_22', 'bun']

[phases.install]
cmds = [
  'curl -fsSL https://bun.sh/install | bash',
  'export BUN_INSTALL="$HOME/.bun"',
  'export PATH="$BUN_INSTALL/bin:$PATH"',
  'bun install'
]

[phases.build]
cmds = ['bun run build']

[start]
cmd = 'bun run start'
