[phases.setup]
aptPkgs = ['unzip', 'curl']
nixPkgs = ['nodejs_22', 'bun']

[phases.install]
cmds = [
  'curl -fsSL https://bun.sh/install | bash',
  'pwd',
  'ls -la $HOME',
  'ls -la $HOME/.bun',
  'bun --version',
  'bun install'
]

[phases.build]
cmds = ['bun run build']

[start]
cmd = 'bun run start'
