# Nixpacks.toml
[phases]
# Specify the installation steps
install = """
    # Install Bun using Nix
    nix-env -iA nixpkgs.bun
"""

# Define the commands for starting the application
[commands]
# This assumes you have an entry point script, e.g., `index.js`
start = "bun install"

# Optionally, define the build command if there is a build step
# [build]
# command = "bun build"

[variables]
# Specify any environment variables needed by Bun
NODE_ENV = "production"
PORT = "3000"