[phases.setup]
aptPkgs = ['unzip', 'curl']
nixpkgs = ['nodejs_22', 'bun']

[phases.build]
# Use Bun to install dependencies
cmds = ["bun install"]

[phases.start]
# Use Bun to start the application
cmds = ["bun start"]

[start]
cmd = "bun run start"